cluster_name = "davidhei-k8s"
aws_region = "us-east-2"
ami_id = "ami-0862be96e41dcbf74"
public_subnet_ids = ["davidhei-public-subnet", "davidhei-public-subnet-2", "davidhei-public-subnet-3"]
control_plane_iam_role = "davidhei-k8s-control-plane-role"
control_plane_sg_ids = ["sg-0e25deee5189c83d9"]
worker_node_iam_role = "davidhei-k8s-worker-node-role"
worker_node_sg_ids = ["sg-0e25deee5189c83d9"]
key_pair_name = "davidhei-ohio-key"
instance_type = "t3.medium"
